import type { IRNode } from '../gltf/ir'
import type { CommandHandler } from '../registry'
import type { TextureFormat } from '../gltf/transform'
import { rmSync } from 'node:fs'
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { basename, dirname, extname, join, resolve } from 'node:path'
import { bold, gray } from 'kolorist'
import { emitSFC } from '../emit/sfc'
import { findPublicRoot, inferAssetURL } from '../emit/url'
import { buildIR } from '../gltf/build-ir'
import { loadGLTFFile } from '../gltf/load'
import { transformGLTF } from '../gltf/transform'
import { detectProject } from '../project'
import * as ui from '../ui'
import { glyph, green } from '../ui/theme'

export interface GLTFOptions {
  url?: string
  output?: string
  slots?: 'named' | 'all' | 'none'
  shadows?: boolean
  keepgroups?: boolean
  keepnames?: boolean
  root?: string
  precision?: number
  meta?: boolean
  console?: boolean
  force?: boolean
  /** Print every slot name instead of the first few. */
  verbose?: boolean
  /** Report what the parser sees without generating anything. */
  dryRun?: boolean
  /** Dump the intermediate representation. */
  json?: boolean
  /** Optimize the model with glTF-Transform before generating against it. */
  transform?: boolean
  /** Batch meshes that share a geometry+material pair into an InstancedMesh. */
  instance?: boolean
  /** Batch every eligible mesh, including the ones that appear once. */
  instanceall?: boolean
  /** Generate colliders from the suffixes on node names. */
  physics?: 'rapier'
  resolution?: number
  format?: TextureFormat
  simplify?: boolean
  ratio?: number
  error?: number
  keepmeshes?: boolean
  keepmaterials?: boolean
}

/** Marks output as ours, so regeneration never eats a hand-written file. */
const GENERATED_MARKER = 'Auto-generated by @tresjs/cli'

/** Slot names printed before the list collapses to a count. `--verbose` lifts the cap. */
const SLOT_PREVIEW = 6

async function isDirectory(path: string): Promise<boolean> {
  return stat(path).then(entry => entry.isDirectory(), () => false)
}

function plural(count: number, noun: string, suffix = 's'): string {
  return `${count} ${noun}${count === 1 ? '' : suffix}`
}

/** Nodes whose name declares collision, misreads included: both are worth reporting. */
function countColliders(node: IRNode): number {
  return (node.physics ? 1 : 0) + node.children.reduce((total, child) => total + countColliders(child), 0)
}

/** The optimized asset lives beside the source as `<name>-transformed.glb`. */
function transformedPath(input: string): string {
  return join(dirname(input), `${basename(input, extname(input))}-transformed.glb`)
}

/** `Robot.gen.vue` → `Robot.instances.gen.vue`, beside the component that imports it. */
function instancesPath(target: string): string {
  return join(dirname(target), basename(target).replace(/(\.gen)?\.vue$/, '.instances$1.vue'))
}

/** `4200000` → `4.0MB`. Enough precision to make the saving obvious, not exact. */
function formatBytes(bytes: number): string {
  if (bytes < 1024) {
    return `${bytes}B`
  }
  const units = ['KB', 'MB', 'GB']
  let value = bytes / 1024
  let unit = 0
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024
    unit++
  }
  return `${value < 10 ? value.toFixed(1) : Math.round(value)}${units[unit]}`
}

/** glTF-Transform names its steps for machines. These are for the person watching. */
const STEP_LABELS: Record<string, string> = {
  dedup: 'deduplicating',
  palette: 'batching materials',
  flatten: 'flattening the hierarchy',
  dequantize: 'dequantizing',
  join: 'merging meshes',
  weld: 'welding vertices',
  simplify: 'simplifying geometry',
  resample: 'resampling animation',
  prune: 'pruning unused data',
  sparse: 'compacting accessors',
  textureCompress: 'compressing textures',
  draco: 'encoding draco',
}

/**
 * Optimize the source into `output` with glTF-Transform, reporting each step as it runs.
 * This is the slow part of a run by a wide margin, so it is the part worth narrating.
 */
async function optimize(input: string, output: string, options: GLTFOptions): Promise<void> {
  await ui.phase(
    'Transform',
    task => transformGLTF(input, output, {
      resolution: options.resolution,
      format: options.format,
      simplify: options.simplify,
      ratio: options.ratio,
      error: options.error,
      // join() welds compatible meshes into one, which is the opposite of what instancing
      // wants: it needs the repeats to stay separate nodes over one deduplicated geometry.
      keepMeshes: options.keepmeshes || Boolean(options.instance || options.instanceall),
      keepMaterials: options.keepmaterials,
      onStep: name => task.update(STEP_LABELS[name] ?? name),
    }).catch(async (error) => {
      throw await explainMissingFile(input, error)
    }),
    ({ before, after }) => {
      const saved = before > 0 ? Math.round((1 - after / before) * 100) : 0
      return `${formatBytes(before)} ${gray(glyph.arrow)} ${formatBytes(after)}  ${green(`-${saved}%`)}`
    },
  )
}

/**
 * `toy-rocket.glb` → `ToyRocket`, so the output is importable as a component. Also read off
 * the output path when `-o` names one, because that is the name the consumer will import,
 * and `--instance` keys its injection on it.
 */
function componentName(input: string): string {
  return basename(input, extname(input))
    .replace(/\.gen$/, '')
    .split(/[^a-z0-9]+/i)
    .filter(Boolean)
    .map(part => part[0].toUpperCase() + part.slice(1))
    .join('') || 'Model'
}

/**
 * `/public/models/x.glb` is the url, not the path, and typing it is the obvious
 * mistake to make. Say so instead of leaving the user with a bare ENOENT.
 */
async function explainMissingFile(input: string, error: unknown): Promise<unknown> {
  if ((error as NodeJS.ErrnoException)?.code !== 'ENOENT' || !input.startsWith('/')) {
    return error
  }

  const relative = input.replace(/^\/+/, '')
  const exists = await readFile(resolve(process.cwd(), relative)).then(() => true, () => false)

  return new Error(
    exists
      ? `${input} does not exist — did you mean ${relative}? Pass the path to the file, not the url it is served from.`
      : `${input} does not exist.`,
  )
}

/**
 * Beside the model is the obvious place, except when the model lives in `public/` —
 * a bundler copies that directory verbatim and never compiles it, so a component
 * written there can never be imported.
 *
 * `models/` rather than `components/` on purpose: component directories are
 * auto-scanned by unplugin-vue-components and Nuxt, and the dot in `.gen.vue`
 * produces an invalid identifier in the generated `components.d.ts`.
 */
async function defaultOutput(input: string): Promise<string> {
  const filename = `${componentName(input)}.gen.vue`
  const publicRoot = await findPublicRoot(input)

  if (!publicRoot) {
    return join(dirname(input), filename)
  }

  const project = await detectProject(dirname(input))
  // With no package.json anywhere above, detection falls back to the model's own
  // directory, which is inside public/ — the one place the file must not go.
  const base = publicRoot.startsWith(project.root) ? project.root : dirname(publicRoot)

  for (const dir of ['src', 'app']) {
    if (await isDirectory(join(base, dir))) {
      return join(base, dir, 'models', filename)
    }
  }

  return join(base, 'models', filename)
}

/**
 * `-o src/models` is the obvious thing to type, and a directory is not a file. Anything not
 * named `.vue` is taken as one: a generated SFC under any other extension cannot be imported
 * by a bundler, so reading an extensionless path as a filename is never what was meant.
 */
function resolveOutput(output: string, input: string): string {
  return output.endsWith('.vue') ? output : join(output, `${componentName(input)}.gen.vue`)
}

/**
 * `-o /src/models` is a project path carrying a leading slash, which the shell reads as the
 * filesystem root — the same slip as passing `/public/models/x.glb` as the input, and just as
 * worth naming instead of leaving an errno behind.
 */
async function explainUnwritablePath(target: string, error: unknown): Promise<unknown> {
  const { code } = (error ?? {}) as NodeJS.ErrnoException
  if (!['ENOENT', 'EACCES', 'EPERM', 'EROFS'].includes(code ?? '') || !target.startsWith('/')) {
    return error
  }

  const relative = target.replace(/^\/+/, '')
  const [root] = relative.split('/')
  // Nobody keeps a `/src` at the filesystem root, so the slash was a slip. `/Users` they do
  // keep, and then the failure is about permissions rather than about the shape of the path.
  const rooted = await isDirectory(`/${root}`)

  return new Error(
    rooted
      ? `Cannot write to ${target}: ${(error as Error)?.message ?? 'the path is not writable'}.`
      : `Cannot write to ${target} — did you mean ${relative}? A leading slash is the filesystem root, not the project root.`,
  )
}

async function assertWritable(path: string, force: boolean): Promise<void> {
  if (force) {
    return
  }

  const existing = await readFile(path, 'utf-8').catch(() => null)
  if (existing !== null && !existing.includes(GENERATED_MARKER)) {
    throw new Error(`${path} was not generated by this tool, so it will not be overwritten. Pass --force to replace it.`)
  }
}

/**
 * Generates a Vue component from a model. Every renderable node becomes a slot whose
 * fallback is the generated markup, so regenerating after an artist re-export never
 * destroys the overrides a consumer wrote in their own file.
 */
const gltf: CommandHandler = async function (input: string, options: GLTFOptions = {}) {
  const wantsInstancing = Boolean(options.instance || options.instanceall)

  ui.header('gltf', basename(input))

  // Batching dedupes by geometry identity, and an unoptimized export hands three one
  // geometry object per node however identical they are — so instancing without the
  // pipeline finds nothing. gltfjsx forces it silently; say it out loud instead.
  if (wantsInstancing && !options.dryRun && !options.json) {
    ui.note('instancing needs deduplicated geometry, so --transform is on and --keepmeshes with it')
  }

  // --json and --dry-run only inspect the source, so there is nothing to optimize for them.
  const wantsTransform = Boolean(options.transform || wantsInstancing) && !options.dryRun && !options.json

  // model: the file the IR is built from. assetSource: the path the url is inferred from.
  // They only diverge in --console mode, where the optimized file is written to a temp dir
  // (so a preview never litters the project) but its url must still point at where the
  // asset would really live, beside the source.
  let model = input
  let assetSource = input
  let tempDir: string | undefined
  // Transforming is the slow phase, so Ctrl-C lands in it more often than anywhere else, and
  // the `finally` below never runs when it does. Cleanup has to be registered, not awaited.
  let releaseTempDir: (() => void) | undefined

  if (wantsTransform) {
    if (options.console) {
      tempDir = await mkdtemp(join(tmpdir(), 'tres-gltf-'))
      releaseTempDir = ui.onExit(() => rmSync(tempDir!, { recursive: true, force: true }))
      const sibling = transformedPath(input)
      model = join(tempDir, basename(sibling))
      assetSource = sibling
      await optimize(input, model, options)
    }
    else {
      model = transformedPath(input)
      assetSource = model
      await optimize(input, model, options)
    }
  }

  try {
    const ir = await ui.phase(
      'Parse',
      () => loadGLTFFile(model)
        .catch(async (error) => {
          throw await explainMissingFile(model, error)
        })
        .then(buildIR),
      parsed => [
        plural(Object.keys(parsed.nodes).length, 'named node'),
        plural(Object.values(parsed.nodes).filter(node => node.type.endsWith('Mesh')).length, 'mesh', 'es'),
        plural(Object.keys(parsed.materials).length, 'material'),
      ].join(gray(' · ')),
    )

    for (const warning of ir.warnings) {
      ui.warn(warning.message)
    }

    if (options.json) {
      ui.payload(JSON.stringify(ir, null, 2))
      return
    }

    if (options.dryRun) {
      // Buckets of one only matter to --instanceall; they are not candidates on their own.
      const candidates = ir.instances.filter(bucket => bucket.nodes.length > 1).length
      // Reported whether or not --physics is on: a level full of suffixes nobody acted on is
      // exactly what the user needs to be told.
      const colliders = countColliders(ir.root)

      ui.note(plural(ir.animations.length, 'animation clip'))
      if (candidates) {
        ui.note(plural(candidates, 'instancing candidate'))
      }
      if (colliders) {
        ui.note(`${plural(colliders, 'collider suffix', 'es')}${options.physics ? '' : ' — pass --physics rapier to generate them'}`)
      }
      ui.note('run without --dry-run to generate a component')
      return
    }

    const asset = options.url ? { url: options.url, inferred: true } : await inferAssetURL(assetSource)
    if (!asset.inferred) {
      ui.warn(`No public/ directory above ${assetSource}, so the model url is a guess: ${asset.url}`)
      ui.note('Pass --url to set it explicitly.')
    }

    // The provider's path is settled before the emit: the consumer imports it by name.
    const target = options.console
      ? undefined
      : options.output ? resolveOutput(options.output, input) : await defaultOutput(input)
    const name = componentName(target ?? input)
    const instancesTarget = instancesPath(target ?? `${name}.gen.vue`)

    const { code, instances, slots, warnings } = await ui.phase(
      'Emit',
      () => emitSFC(ir, {
        url: asset.url,
        name,
        slots: options.slots,
        shadows: options.shadows,
        keepGroups: options.keepgroups,
        keepNames: options.keepnames,
        root: options.root,
        precision: options.precision,
        meta: options.meta,
        instance: options.instance,
        instanceAll: options.instanceall,
        physics: options.physics,
        instancesModule: `./${basename(instancesTarget)}`,
        command: `tres ${process.argv.slice(2).join(' ')}`,
      }),
      emitted => [
        plural(emitted.slots.length, 'slot'),
        ...(options.physics ? [plural(countColliders(ir.root), 'collider')] : []),
      ].join(gray(' · ')),
    )

    for (const warning of warnings) {
      ui.warn(warning)
    }

    if (!target) {
      ui.payload(instances ? `${code}\n<!-- ${basename(instancesTarget)} -->\n${instances}` : code)
      return
    }

    // Not a phase of its own: the list below is the confirmation, and a failure here already
    // says which file it is about.
    const written = instances ? [instancesTarget, target] : [target]
    for (const path of written) {
      await assertWritable(path, Boolean(options.force))
    }
    await mkdir(dirname(target), { recursive: true }).catch(async (error) => {
      throw await explainUnwritablePath(target, error)
    })
    // Past the mkdir there is nothing left to explain: the directory exists, so a failure here
    // is a permission or a disk, and node's own errno already names the file.
    await writeFile(target, code, 'utf-8')
    if (instances) {
      await writeFile(instancesTarget, instances, 'utf-8')
    }

    ui.blank()
    for (const path of written) {
      ui.success(bold(path))
    }
    ui.list('slots', slots, options.verbose ? undefined : SLOT_PREVIEW, 'rerun with --verbose')
    if (wantsTransform) {
      ui.note(`useGLTF() now loads ${basename(model)}`)
    }
    ui.done()
  }
  finally {
    releaseTempDir?.()
    if (tempDir) {
      await rm(tempDir, { recursive: true, force: true }).catch(() => {})
    }
  }
}

export default gltf
