import type { CommandHandler } from '../registry'
import type { TextureFormat } from '../gltf/transform'
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { basename, dirname, extname, join, resolve } from 'node:path'
import { bold, cyan, gray, green, yellow } from 'kolorist'
import { emitSFC } from '../emit/sfc'
import { findPublicRoot, inferAssetURL } from '../emit/url'
import { buildIR } from '../gltf/build-ir'
import { loadGLTFFile } from '../gltf/load'
import { transformGLTF } from '../gltf/transform'
import { detectProject } from '../project'

export interface GLTFOptions {
  url?: string
  output?: string
  slots?: 'named' | 'all' | 'none'
  shadows?: boolean
  keepgroups?: boolean
  keepnames?: boolean
  root?: string
  precision?: number
  meta?: boolean
  console?: boolean
  force?: boolean
  /** Report what the parser sees without generating anything. */
  dryRun?: boolean
  /** Dump the intermediate representation. */
  json?: boolean
  /** Optimize the model with glTF-Transform before generating against it. */
  transform?: boolean
  /** Batch meshes that share a geometry+material pair into an InstancedMesh. */
  instance?: boolean
  /** Batch every eligible mesh, including the ones that appear once. */
  instanceall?: boolean
  resolution?: number
  format?: TextureFormat
  simplify?: boolean
  ratio?: number
  error?: number
  keepmeshes?: boolean
  keepmaterials?: boolean
}

/** Marks output as ours, so regeneration never eats a hand-written file. */
const GENERATED_MARKER = 'Auto-generated by @tresjs/cli'

async function isDirectory(path: string): Promise<boolean> {
  return stat(path).then(entry => entry.isDirectory(), () => false)
}

function plural(count: number, noun: string, suffix = 's'): string {
  return `${count} ${noun}${count === 1 ? '' : suffix}`
}

/** The optimized asset lives beside the source as `<name>-transformed.glb`. */
function transformedPath(input: string): string {
  return join(dirname(input), `${basename(input, extname(input))}-transformed.glb`)
}

/** `Robot.gen.vue` → `Robot.instances.gen.vue`, beside the component that imports it. */
function instancesPath(target: string): string {
  return join(dirname(target), basename(target).replace(/(\.gen)?\.vue$/, '.instances$1.vue'))
}

/** `4200000` → `4.0MB`. Enough precision to make the saving obvious, not exact. */
function formatBytes(bytes: number): string {
  if (bytes < 1024) {
    return `${bytes}B`
  }
  const units = ['KB', 'MB', 'GB']
  let value = bytes / 1024
  let unit = 0
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024
    unit++
  }
  return `${value < 10 ? value.toFixed(1) : Math.round(value)}${units[unit]}`
}

/**
 * Optimize the source into `output` with glTF-Transform. Loud on purpose: the user's
 * `useGLTF()` url is about to change, and that should never be a surprise. `quiet`
 * suppresses that in `--console` mode, where the optimized file is a throwaway.
 */
async function optimize(input: string, output: string, options: GLTFOptions, quiet = false): Promise<void> {
  const { before, after } = await transformGLTF(input, output, {
    resolution: options.resolution,
    format: options.format,
    simplify: options.simplify,
    ratio: options.ratio,
    error: options.error,
    // join() welds compatible meshes into one, which is the opposite of what instancing
    // wants: it needs the repeats to stay separate nodes over one deduplicated geometry.
    keepMeshes: options.keepmeshes || Boolean(options.instance || options.instanceall),
    keepMaterials: options.keepmaterials,
  }).catch(async (error) => {
    throw await explainMissingFile(input, error)
  })

  if (quiet) {
    return
  }

  const saved = before > 0 ? Math.round((1 - after / before) * 100) : 0
  // eslint-disable-next-line no-console
  console.log(`${cyan('⚙')} ${bold(basename(input))} ${gray(`[${formatBytes(before)}]`)} › ${bold(basename(output))} ${gray(`[${formatBytes(after)}]`)} ${green(`(-${saved}%)`)}`)
  // eslint-disable-next-line no-console
  console.log(gray('  the component targets the optimized file; useGLTF() now loads it'))
}

/**
 * `toy-rocket.glb` → `ToyRocket`, so the output is importable as a component. Also read off
 * the output path when `-o` names one, because that is the name the consumer will import,
 * and `--instance` keys its injection on it.
 */
function componentName(input: string): string {
  return basename(input, extname(input))
    .replace(/\.gen$/, '')
    .split(/[^a-z0-9]+/i)
    .filter(Boolean)
    .map(part => part[0].toUpperCase() + part.slice(1))
    .join('') || 'Model'
}

/**
 * `/public/models/x.glb` is the url, not the path, and typing it is the obvious
 * mistake to make. Say so instead of leaving the user with a bare ENOENT.
 */
async function explainMissingFile(input: string, error: unknown): Promise<unknown> {
  if ((error as NodeJS.ErrnoException)?.code !== 'ENOENT' || !input.startsWith('/')) {
    return error
  }

  const relative = input.replace(/^\/+/, '')
  const exists = await readFile(resolve(process.cwd(), relative)).then(() => true, () => false)

  return new Error(
    exists
      ? `${input} does not exist — did you mean ${relative}? Pass the path to the file, not the url it is served from.`
      : `${input} does not exist.`,
  )
}

/**
 * Beside the model is the obvious place, except when the model lives in `public/` —
 * a bundler copies that directory verbatim and never compiles it, so a component
 * written there can never be imported.
 *
 * `models/` rather than `components/` on purpose: component directories are
 * auto-scanned by unplugin-vue-components and Nuxt, and the dot in `.gen.vue`
 * produces an invalid identifier in the generated `components.d.ts`.
 */
async function defaultOutput(input: string): Promise<string> {
  const filename = `${componentName(input)}.gen.vue`
  const publicRoot = await findPublicRoot(input)

  if (!publicRoot) {
    return join(dirname(input), filename)
  }

  const project = await detectProject(dirname(input))
  // With no package.json anywhere above, detection falls back to the model's own
  // directory, which is inside public/ — the one place the file must not go.
  const base = publicRoot.startsWith(project.root) ? project.root : dirname(publicRoot)

  for (const dir of ['src', 'app']) {
    if (await isDirectory(join(base, dir))) {
      return join(base, dir, 'models', filename)
    }
  }

  return join(base, 'models', filename)
}

async function assertWritable(path: string, force: boolean): Promise<void> {
  if (force) {
    return
  }

  const existing = await readFile(path, 'utf-8').catch(() => null)
  if (existing !== null && !existing.includes(GENERATED_MARKER)) {
    throw new Error(`${path} was not generated by this tool, so it will not be overwritten. Pass --force to replace it.`)
  }
}

/**
 * Generates a Vue component from a model. Every renderable node becomes a slot whose
 * fallback is the generated markup, so regenerating after an artist re-export never
 * destroys the overrides a consumer wrote in their own file.
 */
const gltf: CommandHandler = async function (input: string, options: GLTFOptions = {}) {
  const wantsInstancing = Boolean(options.instance || options.instanceall)

  // Batching dedupes by geometry identity, and an unoptimized export hands three one
  // geometry object per node however identical they are — so instancing without the
  // pipeline finds nothing. gltfjsx forces it silently; say it out loud instead.
  if (wantsInstancing && !options.dryRun && !options.json) {
    // eslint-disable-next-line no-console
    console.log(`${cyan('⚙')} instancing needs deduplicated geometry, so --transform is on and --keepmeshes with it`)
  }

  // --json and --dry-run only inspect the source, so there is nothing to optimize for them.
  const wantsTransform = Boolean(options.transform || wantsInstancing) && !options.dryRun && !options.json

  // model: the file the IR is built from. assetSource: the path the url is inferred from.
  // They only diverge in --console mode, where the optimized file is written to a temp dir
  // (so a preview never litters the project) but its url must still point at where the
  // asset would really live, beside the source.
  let model = input
  let assetSource = input
  let tempDir: string | undefined

  if (wantsTransform) {
    if (options.console) {
      tempDir = await mkdtemp(join(tmpdir(), 'tres-gltf-'))
      const sibling = transformedPath(input)
      model = join(tempDir, basename(sibling))
      assetSource = sibling
      await optimize(input, model, options, true)
    }
    else {
      model = transformedPath(input)
      assetSource = model
      await optimize(input, model, options)
    }
  }

  try {
    const ir = buildIR(await loadGLTFFile(model).catch(async (error) => {
      throw await explainMissingFile(model, error)
    }))

    for (const warning of ir.warnings) {
      console.warn(`${yellow('!')} ${warning.message}`)
    }

    if (options.json) {
      // eslint-disable-next-line no-console
      console.log(JSON.stringify(ir, null, 2))
      return
    }

    if (options.dryRun) {
      const meshes = Object.values(ir.nodes).filter(node => node.type.endsWith('Mesh')).length
      // Buckets of one only matter to --instanceall; they are not candidates on their own.
      const candidates = ir.instances.filter(bucket => bucket.nodes.length > 1).length
      // eslint-disable-next-line no-console
      console.log([
        bold(input),
        `  ${plural(Object.keys(ir.nodes).length, 'named node')} (${plural(meshes, 'mesh', 'es')})`,
        `  ${plural(Object.keys(ir.materials).length, 'material')}`,
        `  ${plural(ir.animations.length, 'animation clip')}`,
        candidates ? `  ${plural(candidates, 'instancing candidate')}` : '',
        gray('  run without --dry-run to generate a component'),
      ].filter(Boolean).join('\n'))
      return
    }

    const asset = options.url ? { url: options.url, inferred: true } : await inferAssetURL(assetSource)
    if (!asset.inferred) {
      console.warn(`${yellow('!')} No public/ directory above ${assetSource}, so the model url is a guess: ${asset.url}`)
      console.warn(`  Pass --url to set it explicitly.`)
    }

    // The provider's path is settled before the emit: the consumer imports it by name.
    const target = options.console ? undefined : options.output ?? await defaultOutput(input)
    const name = componentName(target ?? input)
    const instancesTarget = instancesPath(target ?? `${name}.gen.vue`)

    const { code, instances, slots, warnings } = emitSFC(ir, {
      url: asset.url,
      name,
      slots: options.slots,
      shadows: options.shadows,
      keepGroups: options.keepgroups,
      keepNames: options.keepnames,
      root: options.root,
      precision: options.precision,
      meta: options.meta,
      instance: options.instance,
      instanceAll: options.instanceall,
      instancesModule: `./${basename(instancesTarget)}`,
      command: `tres ${process.argv.slice(2).join(' ')}`,
    })

    for (const warning of warnings) {
      console.warn(`${yellow('!')} ${warning}`)
    }

    if (!target) {
      // eslint-disable-next-line no-console
      console.log(instances ? `${code}\n${gray(`<!-- ${basename(instancesTarget)} -->`)}\n${instances}` : code)
      return
    }

    const written = instances ? [instancesTarget, target] : [target]
    for (const path of written) {
      await assertWritable(path, Boolean(options.force))
    }
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, code, 'utf-8')
    if (instances) {
      await writeFile(instancesTarget, instances, 'utf-8')
    }

    // eslint-disable-next-line no-console
    console.log([
      ...written.map(path => `${green('✔')} ${bold(path)}`),
      `  ${plural(slots.length, 'slot')}${slots.length ? gray(`: ${slots.join(', ')}`) : ''}`,
    ].join('\n'))
  }
  finally {
    if (tempDir) {
      await rm(tempDir, { recursive: true, force: true }).catch(() => {})
    }
  }
}

export default gltf
