import type { CommandHandler } from '../registry'
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises'
import { basename, dirname, extname, join, resolve } from 'node:path'
import { bold, gray, green, yellow } from 'kolorist'
import { emitSFC } from '../emit/sfc'
import { findPublicRoot, inferAssetURL } from '../emit/url'
import { buildIR } from '../gltf/build-ir'
import { loadGLTFFile } from '../gltf/load'
import { detectProject } from '../project'

export interface GLTFOptions {
  url?: string
  output?: string
  slots?: 'named' | 'all' | 'none'
  shadows?: boolean
  keepgroups?: boolean
  keepnames?: boolean
  root?: string
  precision?: number
  meta?: boolean
  console?: boolean
  force?: boolean
  /** Report what the parser sees without generating anything. */
  dryRun?: boolean
  /** Dump the intermediate representation. */
  json?: boolean
}

/** Marks output as ours, so regeneration never eats a hand-written file. */
const GENERATED_MARKER = 'Auto-generated by @tresjs/cli'

async function isDirectory(path: string): Promise<boolean> {
  return stat(path).then(entry => entry.isDirectory(), () => false)
}

function plural(count: number, noun: string, suffix = 's'): string {
  return `${count} ${noun}${count === 1 ? '' : suffix}`
}

/** `toy-rocket.glb` → `ToyRocket`, so the output is importable as a component. */
function componentName(input: string): string {
  return basename(input, extname(input))
    .split(/[^a-z0-9]+/i)
    .filter(Boolean)
    .map(part => part[0].toUpperCase() + part.slice(1))
    .join('') || 'Model'
}

/**
 * `/public/models/x.glb` is the url, not the path, and typing it is the obvious
 * mistake to make. Say so instead of leaving the user with a bare ENOENT.
 */
async function explainMissingFile(input: string, error: unknown): Promise<unknown> {
  if ((error as NodeJS.ErrnoException)?.code !== 'ENOENT' || !input.startsWith('/')) {
    return error
  }

  const relative = input.replace(/^\/+/, '')
  const exists = await readFile(resolve(process.cwd(), relative)).then(() => true, () => false)

  return new Error(
    exists
      ? `${input} does not exist — did you mean ${relative}? Pass the path to the file, not the url it is served from.`
      : `${input} does not exist.`,
  )
}

/**
 * Beside the model is the obvious place, except when the model lives in `public/` —
 * a bundler copies that directory verbatim and never compiles it, so a component
 * written there can never be imported.
 *
 * `models/` rather than `components/` on purpose: component directories are
 * auto-scanned by unplugin-vue-components and Nuxt, and the dot in `.gen.vue`
 * produces an invalid identifier in the generated `components.d.ts`.
 */
async function defaultOutput(input: string): Promise<string> {
  const filename = `${componentName(input)}.gen.vue`
  const publicRoot = await findPublicRoot(input)

  if (!publicRoot) {
    return join(dirname(input), filename)
  }

  const project = await detectProject(dirname(input))
  // With no package.json anywhere above, detection falls back to the model's own
  // directory, which is inside public/ — the one place the file must not go.
  const base = publicRoot.startsWith(project.root) ? project.root : dirname(publicRoot)

  for (const dir of ['src', 'app']) {
    if (await isDirectory(join(base, dir))) {
      return join(base, dir, 'models', filename)
    }
  }

  return join(base, 'models', filename)
}

async function assertWritable(path: string, force: boolean): Promise<void> {
  if (force) {
    return
  }

  const existing = await readFile(path, 'utf-8').catch(() => null)
  if (existing !== null && !existing.includes(GENERATED_MARKER)) {
    throw new Error(`${path} was not generated by this tool, so it will not be overwritten. Pass --force to replace it.`)
  }
}

/**
 * Generates a Vue component from a model. Every renderable node becomes a slot whose
 * fallback is the generated markup, so regenerating after an artist re-export never
 * destroys the overrides a consumer wrote in their own file.
 */
const gltf: CommandHandler = async function (input: string, options: GLTFOptions = {}) {
  const ir = buildIR(await loadGLTFFile(input).catch(async (error) => {
    throw await explainMissingFile(input, error)
  }))

  for (const warning of ir.warnings) {
    console.warn(`${yellow('!')} ${warning.message}`)
  }

  if (options.json) {
    // eslint-disable-next-line no-console
    console.log(JSON.stringify(ir, null, 2))
    return
  }

  if (options.dryRun) {
    const meshes = Object.values(ir.nodes).filter(node => node.type.endsWith('Mesh')).length
    // eslint-disable-next-line no-console
    console.log([
      bold(input),
      `  ${plural(Object.keys(ir.nodes).length, 'named node')} (${plural(meshes, 'mesh', 'es')})`,
      `  ${plural(Object.keys(ir.materials).length, 'material')}`,
      `  ${plural(ir.animations.length, 'animation clip')}`,
      ir.instances.length ? `  ${plural(ir.instances.length, 'instancing candidate')}` : '',
      gray('  run without --dry-run to generate a component'),
    ].filter(Boolean).join('\n'))
    return
  }

  const asset = options.url ? { url: options.url, inferred: true } : await inferAssetURL(input)
  if (!asset.inferred) {
    console.warn(`${yellow('!')} No public/ directory above ${input}, so the model url is a guess: ${asset.url}`)
    console.warn(`  Pass --url to set it explicitly.`)
  }

  const { code, slots, warnings } = emitSFC(ir, {
    url: asset.url,
    slots: options.slots,
    shadows: options.shadows,
    keepGroups: options.keepgroups,
    keepNames: options.keepnames,
    root: options.root,
    precision: options.precision,
    meta: options.meta,
    command: `tres ${process.argv.slice(2).join(' ')}`,
  })

  for (const warning of warnings) {
    console.warn(`${yellow('!')} ${warning}`)
  }

  if (options.console) {
    // eslint-disable-next-line no-console
    console.log(code)
    return
  }

  const target = options.output ?? await defaultOutput(input)
  await assertWritable(target, Boolean(options.force))
  await mkdir(dirname(target), { recursive: true })
  await writeFile(target, code, 'utf-8')

  // eslint-disable-next-line no-console
  console.log(`${green('✔')} ${bold(target)}\n  ${plural(slots.length, 'slot')}${slots.length ? gray(`: ${slots.join(', ')}`) : ''}`)
}

export default gltf
