[build.environment]
  COREPACK_INTEGRITY_KEYS = "0"
  NODE_VERSION = "22"

[build]
  command = "pnpm run build && pnpm run docs:generate"
  publish = "docs/dist"

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200

