[build]
publish = "apps/docs/.vitepress/dist"
command = "pnpm install && nx run-many --target=build --projects=@tresjs/core,docs"

[build.environment]
COREPACK_INTEGRITY_KEYS = "0"
NODE_VERSION = "22"
