packages:
  - apps/*
  - packages/*
  - packages/*/playground
  - packages/*/playground/*
  - tools/*

catalog:
  # Core Three.js ecosystem
  three: ^0.180.0
  "@types/three": ^0.180.0
  three-stdlib: ^2.36.0
  three-custom-shader-material: ^5.4.0

  # Vue ecosystem
  vue: ^3.5.21
  "@vueuse/core": ^13.9.0
  vue-tsc: ^3.0.7

  # Build tools
  vite: ^7.1.6
  "@vitejs/plugin-vue": ^6.0.1
  vite-plugin-dts: 4.5.4
  vite-plugin-banner: ^0.8.1
  rollup-plugin-visualizer: ^6.0.3
  rollup-plugin-analyzer: ^4.0.0

  # Dev tools
  eslint: ^9.34.0
  typescript: ^5.8.3
  "@typescript-eslint/eslint-plugin": ^8.42.0
  "@typescript-eslint/parser": ^8.42.0
  eslint-plugin-vue: ^10.4.0

  # Testing
  vitest: 3.2.4
  "@vitest/coverage-v8": ^3.2.4
  "@vitest/ui": ^3.2.4
  "@vue/test-utils": ^2.4.6
  jsdom: ^27.0.0

  # Utilities
  kolorist: ^1.8.0
  pathe: ^2.0.3
  gsap: ^3.13.0
  unocss: ^66.1.2
  vitepress: 1.6.4