packages:
  - apps/*
  - packages/*
  - packages/*/playground
  - packages/*/playground/*
  - tools/*

catalogs:
  build:
    rollup-plugin-analyzer: ^4.0.0
    rollup-plugin-visualizer: ^6.0.3
    tsdown: 0.16.1

  docs:
    vitepress: 1.6.4

  eslint:
    '@typescript-eslint/eslint-plugin': ^8.42.0
    '@typescript-eslint/parser': ^8.42.0
    eslint: ^9.34.0
    eslint-plugin-vue: ^10.4.0

  nuxt:
    '@nuxt/content': ^3.7.1
    '@nuxt/image': ^1.11.0
    '@nuxt/ui': ^4.0.1
    nuxt: 4.1.3

  testing:
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    '@vue/test-utils': ^2.4.6
    jsdom: ^27.0.0
    vitest: 3.2.4

  three:
    '@types/three': ^0.180.0
    three: ^0.180.0
    three-custom-shader-material: ^5.4.0
    three-stdlib: ^2.36.0

  typescript:
    typescript: ^5.8.3
    vue-tsc: ^3.1.1

  utils:
    '@vueuse/core': ^13.9.0
    gsap: ^3.13.0
    kolorist: ^1.8.0
    pathe: ^2.0.3
    unimport: ^5.5.0
    unocss: ^66.1.2
    'unplugin-vue-components': ^30.0.0

  vite:
    '@vitejs/plugin-vue': ^6.0.1
    vite: ^7.1.9
    vite-plugin-banner: ^0.8.1
    vite-plugin-dts: 4.5.4

  vue:
    vue: ^3.5.22
    vue-router: ^4.5.1
