/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlenderCube: typeof import('./.vitepress/theme/components/BlenderCube.vue')['default']
    Cookbook: typeof import('./.vitepress/theme/components/Cookbook.vue')['default']
    DonutExample: typeof import('./.vitepress/theme/components/DonutExample.vue')['default']
    EmbedExperiment: typeof import('./.vitepress/theme/components/EmbedExperiment.vue')['default']
    ExtendExample: typeof import('./.vitepress/theme/components/ExtendExample.vue')['default']
    FirstScene: typeof import('./.vitepress/theme/components/FirstScene.vue')['default']
    FirstSceneLightToon: typeof import('./.vitepress/theme/components/FirstSceneLightToon.vue')['default']
    GraphPane: typeof import('./.vitepress/theme/components/GraphPane.vue')['default']
    HomeSponsors: typeof import('./.vitepress/theme/components/HomeSponsors.vue')['default']
    LocalOrbitControls: typeof import('./.vitepress/theme/components/LocalOrbitControls.vue')['default']
    LoveVueThreeJS: typeof import('./.vitepress/theme/components/LoveVueThreeJS.vue')['default']
    OnDemandRendering: typeof import('./.vitepress/theme/components/OnDemandRendering.vue')['default']
    RenderingLogger: typeof import('./.vitepress/theme/components/RenderingLogger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SandboxDemo: typeof import('./.vitepress/theme/components/SandboxDemo.vue')['default']
    StackBlitzEmbed: typeof import('./.vitepress/theme/components/StackBlitzEmbed.vue')['default']
  }
}
