/**
 * Formatting primitives both emitters need. `--instance` splits the output into a
 * provider and a consumer file, and the two have to agree on how a key is written
 * or the consumer's `nodes.Foo` misses the provider's `nodes['Foo']`.
 */
import type { GLTFIR, Vector3Tuple } from '../gltf/ir'
import * as THREE from 'three'

export const INDENT = '  '

export function isVarName(key: string): boolean {
  return /^[$A-Z_][\w$]*$/i.test(key)
}

/** `nodes.Foo` when it is a legal identifier, `nodes['Foo bar']` when it is not. */
export function access(base: string, key: string): string {
  return isVarName(key) ? `${base}.${key}` : `${base}['${key.replace(/'/g, '\\\'')}']`
}

/**
 * Declares keys the way `quote-props: consistent-as-needed` wants them: bare, unless one
 * key in the block has to be quoted, in which case they all are. A generated file the
 * consumer's linter wants to rewrite is a generated file that fights them on every run.
 */
export function declarer(keys: string[]): (key: string) => string {
  const quoteAll = keys.some(key => !isVarName(key))
  return key => quoteAll ? `'${key.replace(/'/g, '\\\'')}'` : key
}

/**
 * `object.type` is whatever string three stamped on the instance, and not every one of
 * them is a class three exports — a name it does not export would make the generated
 * file fail to compile, so widen to the base class instead.
 */
export function importable(type: string, base: 'Object3D' | 'Material'): string {
  return typeof (THREE as unknown as Record<string, unknown>)[type] === 'function' ? type : base
}

export function round(value: number, precision: number): number {
  const factor = 10 ** precision
  return Math.round(value * factor) / factor
}

export function tuple(values: Vector3Tuple, precision: number): string {
  return `[${values.map(value => round(value, precision)).join(', ')}]`
}

export function header(command: string | undefined, ...notes: string[]): string[] {
  return [
    '/*',
    'Auto-generated by @tresjs/cli. Do not edit.',
    command ? `Command: ${command}` : '',
    ...notes,
    '*/',
  ].filter(Boolean)
}

/**
 * The `ModelNodes` / `ModelMaterials` / `ActionName` declarations. They come straight from
 * the parsed model, so the file describes this export and no other: a re-export that drops
 * a mesh turns into a type error at the override that used it.
 */
export function modelTypes(ir: GLTFIR, exported = false): { lines: string[], threeTypes: Set<string> } {
  const declareNode = declarer(Object.keys(ir.nodes))
  const declareMaterial = declarer(Object.keys(ir.materials))
  const prefix = exported ? 'export ' : ''

  const threeTypes = new Set<string>([
    ...Object.values(ir.nodes).map(entry => importable(entry.type, 'Object3D')),
    ...Object.values(ir.materials).map(entry => importable(entry.type, 'Material')),
  ])
  if (ir.animations.length > 0) {
    threeTypes.add('AnimationClip')
  }

  const lines = [
    `${prefix}interface ModelNodes {`,
    ...Object.entries(ir.nodes)
      .map(([name, entry]) => `${INDENT}${declareNode(name)}: ${importable(entry.type, 'Object3D')}`),
    '}',
    '',
    `${prefix}interface ModelMaterials {`,
    ...Object.entries(ir.materials)
      .map(([name, entry]) => `${INDENT}${declareMaterial(name)}: ${importable(entry.type, 'Material')}`),
    '}',
    // `=` leads its line and the members line up under it: `style/operator-linebreak`,
    // the same shape core writes its own unions in.
    ...(ir.animations.length > 0
      ? [
          '',
          `${prefix}type ActionName`,
          ...ir.animations.map((clip, index) =>
            `${index === 0 ? `${INDENT}= ` : INDENT.repeat(2)}| '${clip.replace(/'/g, '\\\'')}'`),
        ]
      : []),
    '',
  ]

  return { lines, threeTypes }
}
