<script setup lang="ts">
/*
Auto-generated by @tresjs/cli. Do not edit.
Command: tres gltf public/models/Artificer.glb --slots all --force
Override the named slots from the parent instead; regenerating keeps your overrides.
*/
import type { AnimationClip, Bone, Group, Mesh, MeshStandardMaterial, Object3D, SkinnedMesh } from 'three'
import { useAnimations, useGLTF } from '@tresjs/cientos'
import { computed, ref } from 'vue'

interface ModelNodes {
  'Scene': Group
  'Engineer_Rig': Object3D
  'Engineer_ArmLeft': SkinnedMesh
  'Engineer_ArmRight': SkinnedMesh
  'Engineer_Body': SkinnedMesh
  'Engineer_Head': SkinnedMesh
  'Engineer_LegLeft': SkinnedMesh
  'Engineer_LegRight': SkinnedMesh
  'root': Bone
  'hips': Bone
  'spine': Bone
  'chest': Bone
  'upperarml': Bone
  'lowerarml': Bone
  'wristl': Bone
  'handl': Bone
  'handslotl': Bone
  'upperarmr': Bone
  'lowerarmr': Bone
  'wristr': Bone
  'handr': Bone
  'handslotr': Bone
  'head': Bone
  'Engineer_Goggles': Mesh
  'Engineer_Backpack': Mesh
  'upperlegl': Bone
  'lowerlegl': Bone
  'footl': Bone
  'toesl': Bone
  'upperlegr': Bone
  'lowerlegr': Bone
  'footr': Bone
  'toesr': Bone
  'kneeIKl': Bone
  'control-toe-rolll': Bone
  'control-heel-rolll': Bone
  'control-foot-rolll': Bone
  'heelIKl': Bone
  'IK-footl': Bone
  'IK-toel': Bone
  'kneeIKr': Bone
  'control-toe-rollr': Bone
  'control-heel-rollr': Bone
  'control-foot-rollr': Bone
  'heelIKr': Bone
  'IK-footr': Bone
  'IK-toer': Bone
  'elbowIKl': Bone
  'handIKl': Bone
  'elbowIKr': Bone
  'handIKr': Bone
}

interface ModelMaterials {
  engineer_texture: MeshStandardMaterial
}

type ActionName
  = | '1H_Melee_Attack_Chop'
    | '1H_Melee_Attack_Slice_Diagonal'
    | '1H_Melee_Attack_Slice_Horizontal'
    | '1H_Melee_Attack_Stab'
    | '1H_Ranged_Aiming'
    | '1H_Ranged_Reload'
    | '1H_Ranged_Shoot'
    | '1H_Ranged_Shooting'
    | '2H_Melee_Attack_Chop'
    | '2H_Melee_Attack_Slice'
    | '2H_Melee_Attack_Spin'
    | '2H_Melee_Attack_Spinning'
    | '2H_Melee_Attack_Stab'
    | '2H_Melee_Idle'
    | '2H_Ranged_Aiming'
    | '2H_Ranged_Reload'
    | '2H_Ranged_Shoot'
    | '2H_Ranged_Shooting'
    | 'Block'
    | 'Block_Attack'
    | 'Block_Hit'
    | 'Blocking'
    | 'Cheer'
    | 'Death_A'
    | 'Death_A_Pose'
    | 'Death_B'
    | 'Death_B_Pose'
    | 'Dodge_Backward'
    | 'Dodge_Forward'
    | 'Dodge_Left'
    | 'Dodge_Right'
    | 'Dualwield_Melee_Attack_Chop'
    | 'Dualwield_Melee_Attack_Slice'
    | 'Dualwield_Melee_Attack_Stab'
    | 'Hit_A'
    | 'Hit_B'
    | 'Idle'
    | 'Interact'
    | 'Jump_Full_Long'
    | 'Jump_Full_Short'
    | 'Jump_Idle'
    | 'Jump_Land'
    | 'Jump_Start'
    | 'Lie_Down'
    | 'Lie_Idle'
    | 'Lie_Pose'
    | 'Lie_StandUp'
    | 'PickUp'
    | 'Running_A'
    | 'Running_B'
    | 'Running_Strafe_Left'
    | 'Running_Strafe_Right'
    | 'Sit_Chair_Down'
    | 'Sit_Chair_Idle'
    | 'Sit_Chair_Pose'
    | 'Sit_Chair_StandUp'
    | 'Sit_Floor_Down'
    | 'Sit_Floor_Idle'
    | 'Sit_Floor_Pose'
    | 'Sit_Floor_StandUp'
    | 'Spellcast_Long'
    | 'Spellcast_Raise'
    | 'Spellcast_Shoot'
    | 'Spellcasting'
    | 'T-Pose'
    | 'Throw'
    | 'Unarmed_Idle'
    | 'Unarmed_Melee_Attack_Kick'
    | 'Unarmed_Melee_Attack_Punch_A'
    | 'Unarmed_Melee_Attack_Punch_B'
    | 'Unarmed_Pose'
    | 'Use_Item'
    | 'Walking_A'
    | 'Walking_B'
    | 'Walking_Backwards'
    | 'Walking_C'

defineSlots<{
  Engineer_ArmLeft?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Engineer_ArmRight?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Engineer_Body?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Engineer_Head?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Engineer_LegLeft?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Engineer_LegRight?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
}>()

const { state, nodes, materials, isLoading } = useGLTF<ModelNodes, ModelMaterials>('/models/Artificer.glb')

const modelRef = ref()
const animations = computed(() => state.value?.animations ?? [])
const { actions } = useAnimations<AnimationClip, ActionName>(animations, modelRef)

defineExpose({ nodes, materials, actions })
</script>

<template>
  <TresGroup ref="modelRef" :dispose="null">
    <template v-if="!isLoading">
      <slot name="Engineer_ArmLeft" :node="nodes.Engineer_ArmLeft" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_ArmLeft.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_ArmLeft.skeleton" />
      </slot>
      <slot name="Engineer_ArmRight" :node="nodes.Engineer_ArmRight" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_ArmRight.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_ArmRight.skeleton" />
      </slot>
      <slot name="Engineer_Body" :node="nodes.Engineer_Body" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_Body.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_Body.skeleton" />
      </slot>
      <slot name="Engineer_Head" :node="nodes.Engineer_Head" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_Head.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_Head.skeleton" />
      </slot>
      <slot name="Engineer_LegLeft" :node="nodes.Engineer_LegLeft" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_LegLeft.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_LegLeft.skeleton" />
      </slot>
      <slot name="Engineer_LegRight" :node="nodes.Engineer_LegRight" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_LegRight.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_LegRight.skeleton" />
      </slot>
      <primitive :object="nodes.root" />
    </template>
  </TresGroup>
</template>
