<script setup lang="ts">
/*
Auto-generated by @tresjs/cli. Do not edit.
Command: tres gltf public/models/cyber_samurai/cyber_samurai.glb --slots all --force
Override the named slots from the parent instead; regenerating keeps your overrides.
*/
import type { Group, LineBasicMaterial, LineSegments, Mesh, MeshPhysicalMaterial, MeshStandardMaterial, Object3D } from 'three'
import { useGLTF } from '@tresjs/cientos'

interface ModelNodes {
  Sketchfab_Scene: Group
  Sketchfab_model: Object3D
  RoninFinalSobjcleanermaterialmergergles: Object3D
  Object_2: Mesh
  Object_3: Mesh
  Object_4: LineSegments
  Object_5: Mesh
  Object_6: Mesh
  Object_7: Mesh
  Object_8: Mesh
  Object_9: Mesh
  Object_10: Mesh
  Object_11: Mesh
  Object_12: Mesh
  Object_13: Mesh
  Object_14: Mesh
  Object_15: Mesh
  Object_16: Mesh
  Object_17: Mesh
  Object_18: Mesh
  Object_19: Mesh
  Object_20: Mesh
}

interface ModelMaterials {
  Robe2: MeshStandardMaterial
  Robe: MeshPhysicalMaterial
  LowSet3: LineBasicMaterial
  LowSet1: MeshStandardMaterial
  LowSet2: MeshStandardMaterial
}

defineSlots<{
  Object_2?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_3?: (props: { node: Mesh, material: MeshPhysicalMaterial }) => any
  Object_4?: (props: { node: LineSegments, material: LineBasicMaterial }) => any
  Object_5?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_6?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_7?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_8?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_9?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_10?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_11?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_12?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_13?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_14?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_15?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_16?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Object_17?: (props: { node: Mesh, material: LineBasicMaterial }) => any
  Object_18?: (props: { node: Mesh, material: LineBasicMaterial }) => any
  Object_19?: (props: { node: Mesh, material: LineBasicMaterial }) => any
  Object_20?: (props: { node: Mesh, material: LineBasicMaterial }) => any
  Sketchfab_model?: (props: { node: Object3D }) => any
}>()

const { nodes, materials, isLoading } = useGLTF<ModelNodes, ModelMaterials>('/models/cyber_samurai/cyber_samurai.glb')

defineExpose({ nodes, materials })
</script>

<template>
  <TresGroup :dispose="null">
    <template v-if="!isLoading">
      <slot name="Sketchfab_model" :node="nodes.Sketchfab_model">
        <TresGroup :rotation="[-1.57, 0, 0]">
          <slot name="Object_2" :node="nodes.Object_2" :material="materials.Robe2">
            <TresMesh :geometry="nodes.Object_2.geometry" :material="materials.Robe2" />
          </slot>
          <slot name="Object_3" :node="nodes.Object_3" :material="materials.Robe">
            <TresMesh :geometry="nodes.Object_3.geometry" :material="materials.Robe" />
          </slot>
          <slot name="Object_4" :node="nodes.Object_4" :material="materials.LowSet3">
            <TresLineSegments :geometry="nodes.Object_4.geometry" :material="materials.LowSet3" />
          </slot>
          <slot name="Object_5" :node="nodes.Object_5" :material="materials.LowSet1">
            <TresMesh :geometry="nodes.Object_5.geometry" :material="materials.LowSet1" />
          </slot>
          <slot name="Object_6" :node="nodes.Object_6" :material="materials.LowSet1">
            <TresMesh :geometry="nodes.Object_6.geometry" :material="materials.LowSet1" />
          </slot>
          <slot name="Object_7" :node="nodes.Object_7" :material="materials.LowSet1">
            <TresMesh :geometry="nodes.Object_7.geometry" :material="materials.LowSet1" />
          </slot>
          <slot name="Object_8" :node="nodes.Object_8" :material="materials.LowSet1">
            <TresMesh :geometry="nodes.Object_8.geometry" :material="materials.LowSet1" />
          </slot>
          <slot name="Object_9" :node="nodes.Object_9" :material="materials.LowSet2">
            <TresMesh :geometry="nodes.Object_9.geometry" :material="materials.LowSet2" />
          </slot>
          <slot name="Object_10" :node="nodes.Object_10" :material="materials.LowSet2">
            <TresMesh :geometry="nodes.Object_10.geometry" :material="materials.LowSet2" />
          </slot>
          <slot name="Object_11" :node="nodes.Object_11" :material="materials.LowSet2">
            <TresMesh :geometry="nodes.Object_11.geometry" :material="materials.LowSet2" />
          </slot>
          <slot name="Object_12" :node="nodes.Object_12" :material="materials.LowSet2">
            <TresMesh :geometry="nodes.Object_12.geometry" :material="materials.LowSet2" />
          </slot>
          <slot name="Object_13" :node="nodes.Object_13" :material="materials.LowSet2">
            <TresMesh :geometry="nodes.Object_13.geometry" :material="materials.LowSet2" />
          </slot>
          <slot name="Object_14" :node="nodes.Object_14" :material="materials.LowSet2">
            <TresMesh :geometry="nodes.Object_14.geometry" :material="materials.LowSet2" />
          </slot>
          <slot name="Object_15" :node="nodes.Object_15" :material="materials.LowSet2">
            <TresMesh :geometry="nodes.Object_15.geometry" :material="materials.LowSet2" />
          </slot>
          <slot name="Object_16" :node="nodes.Object_16" :material="materials.LowSet2">
            <TresMesh :geometry="nodes.Object_16.geometry" :material="materials.LowSet2" />
          </slot>
          <slot name="Object_17" :node="nodes.Object_17" :material="materials.LowSet3">
            <TresMesh :geometry="nodes.Object_17.geometry" :material="materials.LowSet3" />
          </slot>
          <slot name="Object_18" :node="nodes.Object_18" :material="materials.LowSet3">
            <TresMesh :geometry="nodes.Object_18.geometry" :material="materials.LowSet3" />
          </slot>
          <slot name="Object_19" :node="nodes.Object_19" :material="materials.LowSet3">
            <TresMesh :geometry="nodes.Object_19.geometry" :material="materials.LowSet3" />
          </slot>
          <slot name="Object_20" :node="nodes.Object_20" :material="materials.LowSet3">
            <TresMesh :geometry="nodes.Object_20.geometry" :material="materials.LowSet3" />
          </slot>
        </TresGroup>
      </slot>
    </template>
  </TresGroup>
</template>
