<script setup lang="ts">
/*
Auto-generated by @tresjs/cli. Do not edit.
Command: tres gltf public/models/cyber_samurai/cyber_samurai.glb --instanceall --slots all -o src/models/CyberSamuraiBatched.gen.vue --force
Owns the load and the instanced batches. Render the model inside it:
<CyberSamuraiBatchedInstances><CyberSamuraiBatched /><CyberSamuraiBatched :position="[3, 0, 0]" /></CyberSamuraiBatchedInstances>
*/
import type { Group, LineBasicMaterial, LineSegments, Mesh, MeshPhysicalMaterial, MeshStandardMaterial } from 'three'
import type { ComputedRef } from 'vue'
import { Merged, useGLTF } from '@tresjs/cientos'
import { computed, provide } from 'vue'

// Initial buffer allocation per batch; the batch grows past it if more instances register.
withDefaults(defineProps<{ limit?: number }>(), { limit: 100 })

const { nodes, materials, isLoading } = useGLTF<ModelNodes, ModelMaterials>('/models/cyber_samurai/cyber_samurai-transformed.glb', { draco: true })

// One InstancedMesh per entry. Every <Instance name="..."> in the tree joins the batch
// registered under that key, wherever in the hierarchy it sits.
const meshes = computed(() => ({
  Object_2: nodes.value.Object_2,
  Object_3: nodes.value.Object_3,
  Object_5: nodes.value.Object_5,
  Object_6: nodes.value.Object_6,
  Object_7: nodes.value.Object_7,
  Object_8: nodes.value.Object_8,
  Object_9: nodes.value.Object_9,
  Object_10: nodes.value.Object_10,
  Object_11: nodes.value.Object_11,
  Object_12: nodes.value.Object_12,
  Object_13: nodes.value.Object_13,
  Object_14: nodes.value.Object_14,
  Object_15: nodes.value.Object_15,
  Object_16: nodes.value.Object_16,
  Object_17: nodes.value.Object_17,
  Object_18: nodes.value.Object_18,
  Object_19: nodes.value.Object_19,
  Object_20: nodes.value.Object_20,
}))

provide('tres-gltf:CyberSamuraiBatched', { nodes, materials })

defineExpose({ nodes, materials })
</script>

<script lang="ts">
export interface ModelNodes {
  Sketchfab_Scene: Group
  Object_2: Mesh
  Object_3: Mesh
  Object_4: LineSegments
  Object_5: Mesh
  Object_6: Mesh
  Object_7: Mesh
  Object_8: Mesh
  Object_9: Mesh
  Object_10: Mesh
  Object_11: Mesh
  Object_12: Mesh
  Object_13: Mesh
  Object_14: Mesh
  Object_15: Mesh
  Object_16: Mesh
  Object_17: Mesh
  Object_18: Mesh
  Object_19: Mesh
  Object_20: Mesh
}

export interface ModelMaterials {
  Robe2: MeshStandardMaterial
  Robe: MeshPhysicalMaterial
  LowSet3: LineBasicMaterial
  LowSet1: MeshStandardMaterial
  LowSet2: MeshStandardMaterial
}

/** What the model component injects. Its own file declares none of this. */
export interface ModelContext {
  nodes: ComputedRef<ModelNodes>
  materials: ComputedRef<ModelMaterials>
}
</script>

<template>
  <Merged v-if="!isLoading" :meshes="meshes" :limit="limit">
    <slot></slot>
  </Merged>
</template>
