<script setup lang="ts">
/*
Auto-generated by @tresjs/cli. Do not edit.
Command: tres gltf public/models/Dummy.glb -o src/models
Override the named slots from the parent instead; regenerating keeps your overrides.
*/
import type { Bone, Group, Mesh, MeshStandardMaterial, Object3D, SkinnedMesh } from 'three'
import { useGLTF } from '@tresjs/cientos'

interface ModelNodes {
  Scene: Group
  Rig_Medium: Object3D
  Dummy_ArmLeft: SkinnedMesh
  Dummy_ArmRight: SkinnedMesh
  Dummy_Body: SkinnedMesh
  Dummy_Head: SkinnedMesh
  Dummy_LegLeft: SkinnedMesh
  Dummy_LegRight: SkinnedMesh
  root: Bone
  hips: Bone
  upperlegr: Bone
  lowerlegr: Bone
  footr: Bone
  toesr: Bone
  spine: Bone
  chest: Bone
  upperarmr: Bone
  lowerarmr: Bone
  wristr: Bone
  handr: Bone
  handslotr: Bone
  head: Bone
  Dummy_Helmet: Mesh
  upperarml: Bone
  lowerarml: Bone
  wristl: Bone
  handl: Bone
  handslotl: Bone
  Dummy_TargetOnHisBack: Mesh
  upperlegl: Bone
  lowerlegl: Bone
  footl: Bone
  toesl: Bone
}

interface ModelMaterials {
  prototype_texture: MeshStandardMaterial
}

defineSlots<{
  Dummy_ArmLeft?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Dummy_ArmRight?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Dummy_Body?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Dummy_Head?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Dummy_LegLeft?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Dummy_LegRight?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
}>()

const { nodes, materials, isLoading } = useGLTF<ModelNodes, ModelMaterials>('/models/Dummy.glb')

defineExpose({ nodes, materials })
</script>

<template>
  <TresGroup :dispose="null">
    <template v-if="!isLoading">
      <slot name="Dummy_ArmLeft" :node="nodes.Dummy_ArmLeft" :material="materials.prototype_texture">
        <TresSkinnedMesh :geometry="nodes.Dummy_ArmLeft.geometry" :material="materials.prototype_texture" :skeleton="nodes.Dummy_ArmLeft.skeleton" />
      </slot>
      <slot name="Dummy_ArmRight" :node="nodes.Dummy_ArmRight" :material="materials.prototype_texture">
        <TresSkinnedMesh :geometry="nodes.Dummy_ArmRight.geometry" :material="materials.prototype_texture" :skeleton="nodes.Dummy_ArmRight.skeleton" />
      </slot>
      <slot name="Dummy_Body" :node="nodes.Dummy_Body" :material="materials.prototype_texture">
        <TresSkinnedMesh :geometry="nodes.Dummy_Body.geometry" :material="materials.prototype_texture" :skeleton="nodes.Dummy_Body.skeleton" />
      </slot>
      <slot name="Dummy_Head" :node="nodes.Dummy_Head" :material="materials.prototype_texture">
        <TresSkinnedMesh :geometry="nodes.Dummy_Head.geometry" :material="materials.prototype_texture" :skeleton="nodes.Dummy_Head.skeleton" />
      </slot>
      <slot name="Dummy_LegLeft" :node="nodes.Dummy_LegLeft" :material="materials.prototype_texture">
        <TresSkinnedMesh :geometry="nodes.Dummy_LegLeft.geometry" :material="materials.prototype_texture" :skeleton="nodes.Dummy_LegLeft.skeleton" />
      </slot>
      <slot name="Dummy_LegRight" :node="nodes.Dummy_LegRight" :material="materials.prototype_texture">
        <TresSkinnedMesh :geometry="nodes.Dummy_LegRight.geometry" :material="materials.prototype_texture" :skeleton="nodes.Dummy_LegRight.skeleton" />
      </slot>
      <primitive :object="nodes.root" />
    </template>
  </TresGroup>
</template>
