<script setup lang="ts">
/*
Auto-generated by @tresjs/cli. Do not edit.
Command: tres gltf public/models/Engineer.glb -a public/models/animations/Rig_Medium/Rig_Medium_General.glb -a public/models/animations/Rig_Medium/Rig_Medium_MovementBasic.glb -a public/models/animations/Rig_Medium/Rig_Medium_MovementAdvanced.glb -o src/models --force
Override the named slots from the parent instead; regenerating keeps your overrides.
*/
import type { AnimationClip, Bone, Group, Mesh, MeshStandardMaterial, Object3D, SkinnedMesh } from 'three'
import { useAnimations, useGLTF } from '@tresjs/cientos'
import { computed, ref } from 'vue'

interface ModelNodes {
  'Scene': Group
  'Engineer_Rig': Object3D
  'Engineer_ArmLeft': SkinnedMesh
  'Engineer_ArmRight': SkinnedMesh
  'Engineer_Body': SkinnedMesh
  'Engineer_Head': SkinnedMesh
  'Engineer_LegLeft': SkinnedMesh
  'Engineer_LegRight': SkinnedMesh
  'root': Bone
  'hips': Bone
  'spine': Bone
  'chest': Bone
  'upperarml': Bone
  'lowerarml': Bone
  'wristl': Bone
  'handl': Bone
  'handslotl': Bone
  'upperarmr': Bone
  'lowerarmr': Bone
  'wristr': Bone
  'handr': Bone
  'handslotr': Bone
  'head': Bone
  'Engineer_Goggles': Mesh
  'Engineer_Backpack': Mesh
  'upperlegl': Bone
  'lowerlegl': Bone
  'footl': Bone
  'toesl': Bone
  'upperlegr': Bone
  'lowerlegr': Bone
  'footr': Bone
  'toesr': Bone
  'kneeIKl': Bone
  'control-toe-rolll': Bone
  'control-heel-rolll': Bone
  'control-foot-rolll': Bone
  'heelIKl': Bone
  'IK-footl': Bone
  'IK-toel': Bone
  'kneeIKr': Bone
  'control-toe-rollr': Bone
  'control-heel-rollr': Bone
  'control-foot-rollr': Bone
  'heelIKr': Bone
  'IK-footr': Bone
  'IK-toer': Bone
  'elbowIKl': Bone
  'handIKl': Bone
  'elbowIKr': Bone
  'handIKr': Bone
}

interface ModelMaterials {
  engineer_texture: MeshStandardMaterial
}

type ActionName
  = | 'Death_A'
    | 'Death_A_Pose'
    | 'Death_B'
    | 'Death_B_Pose'
    | 'Hit_A'
    | 'Hit_B'
    | 'Idle_A'
    | 'Idle_B'
    | 'Interact'
    | 'PickUp'
    | 'Spawn_Air'
    | 'Spawn_Ground'
    | 'T-Pose'
    | 'Throw'
    | 'Use_Item'
    | 'Jump_Full_Long'
    | 'Jump_Full_Short'
    | 'Jump_Idle'
    | 'Jump_Land'
    | 'Jump_Start'
    | 'Running_A'
    | 'Running_B'
    | 'Walking_A'
    | 'Walking_B'
    | 'Walking_C'
    | 'Crawling'
    | 'Crouching'
    | 'Dodge_Backward'
    | 'Dodge_Forward'
    | 'Dodge_Left'
    | 'Dodge_Right'
    | 'Running_HoldingBow'
    | 'Running_HoldingRifle'
    | 'Running_Strafe_Left'
    | 'Running_Strafe_Right'
    | 'Sneaking'
    | 'Walking_Backwards'

defineSlots<{
  Engineer_ArmLeft?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Engineer_ArmRight?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Engineer_Body?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Engineer_Head?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Engineer_LegLeft?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
  Engineer_LegRight?: (props: { node: SkinnedMesh, material: MeshStandardMaterial }) => any
}>()

const { nodes, materials, isLoading } = useGLTF<ModelNodes, ModelMaterials>('/models/Engineer.glb')
const { state: rigMediumGeneral } = useGLTF('/models/animations/Rig_Medium/Rig_Medium_General.glb')
const { state: rigMediumMovementBasic } = useGLTF('/models/animations/Rig_Medium/Rig_Medium_MovementBasic.glb')
const { state: rigMediumMovementAdvanced } = useGLTF('/models/animations/Rig_Medium/Rig_Medium_MovementAdvanced.glb')

const animations = computed(() => {
  // The mixer resolves every track against a node name in the rendered tree and never
  // retries a miss, so the clips must not reach it before the model they drive.
  if (isLoading.value) {
    return []
  }

  return [
    ...(rigMediumGeneral.value?.animations ?? []),
    ...(rigMediumMovementBasic.value?.animations ?? []),
    ...(rigMediumMovementAdvanced.value?.animations ?? []),
  ]
})
const modelRef = ref()
const { actions } = useAnimations<AnimationClip, ActionName>(animations, modelRef)

defineExpose({ nodes, materials, actions })
</script>

<template>
  <TresGroup ref="modelRef" :dispose="null">
    <template v-if="!isLoading">
      <slot name="Engineer_ArmLeft" :node="nodes.Engineer_ArmLeft" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_ArmLeft.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_ArmLeft.skeleton" />
      </slot>
      <slot name="Engineer_ArmRight" :node="nodes.Engineer_ArmRight" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_ArmRight.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_ArmRight.skeleton" />
      </slot>
      <slot name="Engineer_Body" :node="nodes.Engineer_Body" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_Body.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_Body.skeleton" />
      </slot>
      <slot name="Engineer_Head" :node="nodes.Engineer_Head" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_Head.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_Head.skeleton" />
      </slot>
      <slot name="Engineer_LegLeft" :node="nodes.Engineer_LegLeft" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_LegLeft.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_LegLeft.skeleton" />
      </slot>
      <slot name="Engineer_LegRight" :node="nodes.Engineer_LegRight" :material="materials.engineer_texture">
        <TresSkinnedMesh :geometry="nodes.Engineer_LegRight.geometry" :material="materials.engineer_texture" :skeleton="nodes.Engineer_LegRight.skeleton" />
      </slot>
      <primitive :object="nodes.root" />
    </template>
  </TresGroup>
</template>
