<script setup lang="ts">
/*
Auto-generated by @tresjs/cli. Do not edit.
Command: tres gltf public/models/level.glb -o src/models/Level.gen.vue --physics rapier
Override the named slots from the parent instead; regenerating keeps your overrides.
Colliders come from the suffixes on the node names. Render this inside <Physics> from
'@tresjs/rapier', or the bodies never simulate.
*/
import type { Group, Mesh, MeshStandardMaterial } from 'three'
import { useGLTF } from '@tresjs/cientos'
import { RigidBody } from '@tresjs/rapier'

interface ModelNodes {
  'Scene': Group
  'Floor-convcol': Mesh
  'Cube_Prototype_Large_A-convcol': Mesh
  'Primitive_Slope-convcol': Mesh
  'Cube_Prototype_Large_A001-convcol': Mesh
  'Primitive_Beam-convcol': Mesh
  'Primitive_Stairs_Half': Mesh
  'Primitive_Stairs_Half_Collision-convcolonly': Mesh
  'Primitive_Cube_Small-convcol': Mesh
  'Primitive_Stairs': Mesh
  'Primitive_Stairs_Collision-convcolonly': Mesh
  'Floor_Prototype-col': Mesh
  'table_medium-col': Mesh
  'Can_A-rigid': Mesh
  'Can_B-rigid': Mesh
  'Can_A001-rigid': Mesh
  'Can_B001-rigid': Mesh
}

interface ModelMaterials {
  'prototype_texture': MeshStandardMaterial
  'prototype_texture.001': MeshStandardMaterial
  'prototype_texture.002': MeshStandardMaterial
  'prototype_texture.003': MeshStandardMaterial
  'prototype_texture.004': MeshStandardMaterial
}

defineSlots<{
  'Floor-convcol'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Cube_Prototype_Large_A-convcol'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Primitive_Slope-convcol'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Cube_Prototype_Large_A001-convcol'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Primitive_Beam-convcol'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Primitive_Stairs_Half_Collision-convcolonly'?: (props: { node: Mesh }) => any
  'Primitive_Stairs_Half'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Primitive_Cube_Small-convcol'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Primitive_Stairs_Collision-convcolonly'?: (props: { node: Mesh }) => any
  'Primitive_Stairs'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Floor_Prototype-col'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'table_medium-col'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Can_A-rigid'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Can_B-rigid'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Can_A001-rigid'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  'Can_B001-rigid'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
}>()

const { nodes, materials, isLoading } = useGLTF<ModelNodes, ModelMaterials>('/models/level.glb', { draco: true })

defineExpose({ nodes, materials })
</script>

<template>
  <TresGroup :dispose="null">
    <template v-if="!isLoading">
      <slot name="Floor-convcol" :node="nodes['Floor-convcol']" :material="materials.prototype_texture">
        <RigidBody type="fixed" collider="convexHull">
          <TresMesh :geometry="nodes['Floor-convcol'].geometry" :material="materials.prototype_texture" />
        </RigidBody>
      </slot>
      <slot name="Cube_Prototype_Large_A-convcol" :node="nodes['Cube_Prototype_Large_A-convcol']" :material="materials.prototype_texture">
        <RigidBody type="fixed" collider="convexHull">
          <TresMesh :geometry="nodes['Cube_Prototype_Large_A-convcol'].geometry" :material="materials.prototype_texture" />
        </RigidBody>
      </slot>
      <slot name="Primitive_Slope-convcol" :node="nodes['Primitive_Slope-convcol']" :material="materials.prototype_texture">
        <RigidBody type="fixed" collider="convexHull">
          <TresMesh :geometry="nodes['Primitive_Slope-convcol'].geometry" :material="materials.prototype_texture" />
        </RigidBody>
      </slot>
      <slot name="Cube_Prototype_Large_A001-convcol" :node="nodes['Cube_Prototype_Large_A001-convcol']" :material="materials.prototype_texture">
        <RigidBody type="fixed" collider="convexHull">
          <TresMesh :geometry="nodes['Cube_Prototype_Large_A001-convcol'].geometry" :material="materials.prototype_texture" />
        </RigidBody>
      </slot>
      <slot name="Primitive_Beam-convcol" :node="nodes['Primitive_Beam-convcol']" :material="materials.prototype_texture">
        <RigidBody type="fixed" collider="convexHull">
          <TresMesh :geometry="nodes['Primitive_Beam-convcol'].geometry" :material="materials.prototype_texture" />
        </RigidBody>
      </slot>
      <slot name="Primitive_Stairs_Half" :node="nodes.Primitive_Stairs_Half" :material="materials.prototype_texture">
        <TresMesh :geometry="nodes.Primitive_Stairs_Half.geometry" :material="materials.prototype_texture">
          <slot name="Primitive_Stairs_Half_Collision-convcolonly" :node="nodes['Primitive_Stairs_Half_Collision-convcolonly']">
            <RigidBody type="fixed" collider="convexHull">
              <TresMesh :geometry="nodes['Primitive_Stairs_Half_Collision-convcolonly'].geometry" :visible="false" />
            </RigidBody>
          </slot>
        </TresMesh>
      </slot>
      <slot name="Primitive_Cube_Small-convcol" :node="nodes['Primitive_Cube_Small-convcol']" :material="materials.prototype_texture">
        <RigidBody type="fixed" collider="convexHull">
          <TresMesh :geometry="nodes['Primitive_Cube_Small-convcol'].geometry" :material="materials.prototype_texture" />
        </RigidBody>
      </slot>
      <slot name="Primitive_Stairs" :node="nodes.Primitive_Stairs" :material="materials.prototype_texture">
        <TresMesh :geometry="nodes.Primitive_Stairs.geometry" :material="materials.prototype_texture">
          <slot name="Primitive_Stairs_Collision-convcolonly" :node="nodes['Primitive_Stairs_Collision-convcolonly']">
            <RigidBody type="fixed" collider="convexHull">
              <TresMesh :geometry="nodes['Primitive_Stairs_Collision-convcolonly'].geometry" :visible="false" />
            </RigidBody>
          </slot>
        </TresMesh>
      </slot>
      <slot name="Floor_Prototype-col" :node="nodes['Floor_Prototype-col']" :material="materials['prototype_texture.001']">
        <RigidBody type="fixed" collider="trimesh">
          <TresMesh :geometry="nodes['Floor_Prototype-col'].geometry" :material="materials['prototype_texture.001']" />
        </RigidBody>
      </slot>
      <slot name="table_medium-col" :node="nodes['table_medium-col']" :material="materials['prototype_texture.002']">
        <RigidBody type="fixed" collider="trimesh">
          <TresMesh :geometry="nodes['table_medium-col'].geometry" :material="materials['prototype_texture.002']" />
        </RigidBody>
      </slot>
      <slot name="Can_A-rigid" :node="nodes['Can_A-rigid']" :material="materials['prototype_texture.003']">
        <RigidBody type="dynamic" collider="convexHull">
          <TresMesh :geometry="nodes['Can_A-rigid'].geometry" :material="materials['prototype_texture.003']" />
        </RigidBody>
      </slot>
      <slot name="Can_B-rigid" :node="nodes['Can_B-rigid']" :material="materials['prototype_texture.004']">
        <RigidBody type="dynamic" collider="convexHull">
          <TresMesh :geometry="nodes['Can_B-rigid'].geometry" :material="materials['prototype_texture.004']" />
        </RigidBody>
      </slot>
      <slot name="Can_A001-rigid" :node="nodes['Can_A001-rigid']" :material="materials['prototype_texture.003']">
        <RigidBody type="dynamic" collider="convexHull">
          <TresMesh :geometry="nodes['Can_A001-rigid'].geometry" :material="materials['prototype_texture.003']" />
        </RigidBody>
      </slot>
      <slot name="Can_B001-rigid" :node="nodes['Can_B001-rigid']" :material="materials['prototype_texture.004']">
        <RigidBody type="dynamic" collider="convexHull">
          <TresMesh :geometry="nodes['Can_B001-rigid'].geometry" :material="materials['prototype_texture.004']" />
        </RigidBody>
      </slot>
    </template>
  </TresGroup>
</template>
