/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlenderCube: typeof import('./src/components/BlenderCube.vue')['default']
    DynamicModel: typeof import('./src/components/DynamicModel.vue')['default']
    LocalOrbitControls: typeof import('./src/components/LocalOrbitControls.vue')['default']
    OverlayInfo: typeof import('./src/components/OverlayInfo.vue')['default']
    ProvideBridge: typeof import('./src/components/ProvideBridge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestResult: typeof import('./src/components/TestResult.vue')['default']
    Tests: typeof import('./src/components/Tests.vue')['default']
    TheExperience: typeof import('./src/components/TheExperience.vue')['default']
    TheSphere: typeof import('./src/components/TheSphere.vue')['default']
  }
}
