# From https://github.com/remirror/template/blob/4f8c5f5629a081217672a8cce1df085510f43913/.github/actions/pnpm/action.yml
name: 'pnpm installation'
description: 'Install and audit dependencies for pnpm'
inputs:
  cache: # id of input
    description: 'The location of the pnpm cache'
    required: true
    default: '.pnpm-store'
  version: # id of input
    description: 'The version to use'
    required: false
    default: 6.10.0

runs:
  using: 'composite'
  steps:
    - name: install pnpm
      run: npm install pnpm@${{ inputs.version }} -g
      shell: bash

    - name: setup pnpm config
      run: pnpm config set store-dir ${{ inputs.cache }}
      shell: bash

    - name: install dependencies
      run: pnpm install --shamefully-hoist
      shell: bash
