/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicScene: typeof import('./src/components/BasicScene.vue')['default']
    BlenderCube: typeof import('./src/components/BlenderCube.vue')['default']
    Ducky: typeof import('./src/components/Ducky.vue')['default']
    DynamicModel: typeof import('./src/components/DynamicModel.vue')['default']
    EffectListItem: typeof import('./src/components/EffectListItem.vue')['default']
    LocalOrbitControls: typeof import('./src/components/LocalOrbitControls.vue')['default']
    OverlayInfo: typeof import('./src/components/OverlayInfo.vue')['default']
    ProvideBridge: typeof import('./src/components/ProvideBridge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestResult: typeof import('./src/components/TestResult.vue')['default']
    Tests: typeof import('./src/components/Tests.vue')['default']
    TheExperience: typeof import('./src/components/TheExperience.vue')['default']
    TheSphere: typeof import('./src/components/TheSphere.vue')['default']
  }
}

// For TSX support
declare global {
  const BasicScene: typeof import('./src/components/BasicScene.vue')['default']
  const BlenderCube: typeof import('./src/components/BlenderCube.vue')['default']
  const Ducky: typeof import('./src/components/Ducky.vue')['default']
  const DynamicModel: typeof import('./src/components/DynamicModel.vue')['default']
  const EffectListItem: typeof import('./src/components/EffectListItem.vue')['default']
  const LocalOrbitControls: typeof import('./src/components/LocalOrbitControls.vue')['default']
  const OverlayInfo: typeof import('./src/components/OverlayInfo.vue')['default']
  const ProvideBridge: typeof import('./src/components/ProvideBridge.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TestResult: typeof import('./src/components/TestResult.vue')['default']
  const Tests: typeof import('./src/components/Tests.vue')['default']
  const TheExperience: typeof import('./src/components/TheExperience.vue')['default']
  const TheSphere: typeof import('./src/components/TheSphere.vue')['default']
}