/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicScene: typeof import('./src/components/BasicScene.vue')['default']
    BlenderCube: typeof import('./src/components/BlenderCube.vue')['default']
    Ducky: typeof import('./src/components/Ducky.vue')['default']
    EffectListItem: typeof import('./src/components/EffectListItem.vue')['default']
    GlitchDemo: typeof import('./src/components/GlitchDemo.vue')['default']
    GraphPane: typeof import('./src/components/GraphPane.vue')['default']
    NoiseDemo: typeof import('./src/components/NoiseDemo.vue')['default']
    OutlineDemo: typeof import('./src/components/OutlineDemo.vue')['default']
    RouteListItem: typeof import('./src/components/RouteListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheExperience: typeof import('./src/components/TheExperience.vue')['default']
    UnrealBloom: typeof import('./src/components/UnrealBloom.vue')['default']
  }
}
