export * from './colliders'
export { default as InstancedRigidBody } from './InstancedRigidBody.vue'
export * from './joints'
export { default as Physics } from './Physics.vue'
export { default as RigidBody } from './RigidBody.vue'
