/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AkuAku: typeof import('./src/components/gltf/BlenderCube.vue')['default']
    BlenderCube: typeof import('./src/components/gltf/BlenderCube.vue')['default']
    FboCube: typeof import('./src/components/FboCube.vue')['default']
    Gltf: typeof import('./src/components/gltf/index.vue')['default']
    GraphPane: typeof import('./src/components/GraphPane.vue')['default']
    Jeep: typeof import('./src/components/fbx/Jeep.vue')['default']
    ModelsDemo: typeof import('./src/components/ModelsDemo.vue')['default']
    OverlayInfo: typeof import('./src/components/OverlayInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarsForTest: typeof import('./src/components/StarsForTest.vue')['default']
  }
}
