<script setup lang="ts">
/*
Auto-generated by @tresjs/cli (SPIKE)
Command: gltf /Users/alvarosabu/Projects/tres/tres/apps/playground/public/models/cyber_samurai/cyber_samurai.glb --slots named --shadows --keepnames
Do not edit. Override via slots from the parent instead.
*/
import { useGLTF } from '@tresjs/cientos'

const { nodes, materials, isLoading } = useGLTF('/models/cyber_samurai/cyber_samurai.glb')

defineExpose({ nodes, materials })
</script>

<template>
  <TresGroup v-if="!isLoading" :dispose="null">
    <TresGroup name="Sketchfab_model">
      <TresGroup name="RoninFinalS_obj_cleaner_materialmerger_gles">
        <slot name="Object_2" :node="nodes.Object_2" :material="materials.Robe2">
          <TresMesh name="Object_2" cast-shadow receive-shadow :geometry="nodes.Object_2.geometry" :material="materials.Robe2" />
        </slot>
        <slot name="Object_3" :node="nodes.Object_3" :material="materials.Robe">
          <TresMesh name="Object_3" cast-shadow receive-shadow :geometry="nodes.Object_3.geometry" :material="materials.Robe" />
        </slot>
        <slot name="Object_4" :node="nodes.Object_4" :material="materials.LowSet3">
          <TresMesh name="Object_4" cast-shadow receive-shadow :geometry="nodes.Object_4.geometry" :material="materials.LowSet3" />
        </slot>
        <slot name="Object_5" :node="nodes.Object_5" :material="materials.LowSet1">
          <TresMesh name="Object_5" cast-shadow receive-shadow :geometry="nodes.Object_5.geometry" :material="materials.LowSet1" />
        </slot>
        <slot name="Object_6" :node="nodes.Object_6" :material="materials.LowSet1">
          <TresMesh name="Object_6" cast-shadow receive-shadow :geometry="nodes.Object_6.geometry" :material="materials.LowSet1" />
        </slot>
        <slot name="Object_7" :node="nodes.Object_7" :material="materials.LowSet1">
          <TresMesh name="Object_7" cast-shadow receive-shadow :geometry="nodes.Object_7.geometry" :material="materials.LowSet1" />
        </slot>
        <slot name="Object_8" :node="nodes.Object_8" :material="materials.LowSet1">
          <TresMesh name="Object_8" cast-shadow receive-shadow :geometry="nodes.Object_8.geometry" :material="materials.LowSet1" />
        </slot>
        <slot name="Object_9" :node="nodes.Object_9" :material="materials.LowSet2">
          <TresMesh name="Object_9" cast-shadow receive-shadow :geometry="nodes.Object_9.geometry" :material="materials.LowSet2" />
        </slot>
        <slot name="Object_10" :node="nodes.Object_10" :material="materials.LowSet2">
          <TresMesh name="Object_10" cast-shadow receive-shadow :geometry="nodes.Object_10.geometry" :material="materials.LowSet2" />
        </slot>
        <slot name="Object_11" :node="nodes.Object_11" :material="materials.LowSet2">
          <TresMesh name="Object_11" cast-shadow receive-shadow :geometry="nodes.Object_11.geometry" :material="materials.LowSet2" />
        </slot>
        <slot name="Object_12" :node="nodes.Object_12" :material="materials.LowSet2">
          <TresMesh name="Object_12" cast-shadow receive-shadow :geometry="nodes.Object_12.geometry" :material="materials.LowSet2" />
        </slot>
        <slot name="Object_13" :node="nodes.Object_13" :material="materials.LowSet2">
          <TresMesh name="Object_13" cast-shadow receive-shadow :geometry="nodes.Object_13.geometry" :material="materials.LowSet2" />
        </slot>
        <slot name="Object_14" :node="nodes.Object_14" :material="materials.LowSet2">
          <TresMesh name="Object_14" cast-shadow receive-shadow :geometry="nodes.Object_14.geometry" :material="materials.LowSet2" />
        </slot>
        <slot name="Object_15" :node="nodes.Object_15" :material="materials.LowSet2">
          <TresMesh name="Object_15" cast-shadow receive-shadow :geometry="nodes.Object_15.geometry" :material="materials.LowSet2" />
        </slot>
        <slot name="Object_16" :node="nodes.Object_16" :material="materials.LowSet2">
          <TresMesh name="Object_16" cast-shadow receive-shadow :geometry="nodes.Object_16.geometry" :material="materials.LowSet2" />
        </slot>
        <slot name="Object_17" :node="nodes.Object_17" :material="materials.LowSet3">
          <TresMesh name="Object_17" cast-shadow receive-shadow :geometry="nodes.Object_17.geometry" :material="materials.LowSet3" />
        </slot>
        <slot name="Object_18" :node="nodes.Object_18" :material="materials.LowSet3">
          <TresMesh name="Object_18" cast-shadow receive-shadow :geometry="nodes.Object_18.geometry" :material="materials.LowSet3" />
        </slot>
        <slot name="Object_19" :node="nodes.Object_19" :material="materials.LowSet3">
          <TresMesh name="Object_19" cast-shadow receive-shadow :geometry="nodes.Object_19.geometry" :material="materials.LowSet3" />
        </slot>
        <slot name="Object_20" :node="nodes.Object_20" :material="materials.LowSet3">
          <TresMesh name="Object_20" cast-shadow receive-shadow :geometry="nodes.Object_20.geometry" :material="materials.LowSet3" />
        </slot>
      </TresGroup>
    </TresGroup>
  </TresGroup>
</template>
