<script setup lang="ts">
/*
Auto-generated by @tresjs/cli. Do not edit.
Command: tres gltf public/models/damaged-helmet/DamagedHelmet.glb --transform
Override the named slots from the parent instead; regenerating keeps your overrides.
*/
import type { Group, Mesh, MeshStandardMaterial } from 'three'
import { useGLTF } from '@tresjs/cientos'

interface ModelNodes {
  'Scene': Group
  'node_damagedHelmet_-6514': Mesh
}

interface ModelMaterials {
  Material_MR: MeshStandardMaterial
}

defineSlots<{
  'node_damagedHelmet_-6514'?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
}>()

const { nodes, materials, isLoading } = useGLTF<ModelNodes, ModelMaterials>('/models/damaged-helmet/DamagedHelmet-transformed.glb', { draco: true })

defineExpose({ nodes, materials })
</script>

<template>
  <TresGroup :dispose="null">
    <template v-if="!isLoading">
      <slot name="node_damagedHelmet_-6514" :node="nodes['node_damagedHelmet_-6514']" :material="materials.Material_MR">
        <TresMesh :geometry="nodes['node_damagedHelmet_-6514'].geometry" :material="materials.Material_MR" :rotation="[1.57, 0, 0]" />
      </slot>
    </template>
  </TresGroup>
</template>
