/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AkuAku: typeof import('./src/components/gltf/AkuAku.vue')['default']
    AnimatedModel: typeof import('./src/components/AnimatedModel.vue')['default']
    FBXModels: typeof import('./src/components/FBXModels.vue')['default']
    Responsiveness: typeof import('./src/components/Responsiveness.vue')['default']
    Shapes: typeof import('./src/components/Shapes.vue')['default']
    TestSphere: typeof import('./src/components/TestSphere.vue')['default']
    Text3D: typeof import('./src/components/Text3D.vue')['default']
    TheBasic: typeof import('./src/components/TheBasic.vue')['default']
    TheEnvironment: typeof import('./src/components/TheEnvironment.vue')['default']
    TheEvents: typeof import('./src/components/TheEvents.vue')['default']
    TheExperience: typeof import('./src/components/TheExperience.vue')['default']
    TheExperiment: typeof import('./src/components/gltf/TheExperiment.vue')['default']
    TheGizmos: typeof import('./src/components/TheGizmos.vue')['default']
    TheGroups: typeof import('./src/components/TheGroups.vue')['default']
    TheParticles: typeof import('./src/components/TheParticles.vue')['default']
    TheSmallExperience: typeof import('./src/components/TheSmallExperience.vue')['default']
    VectorSetProps: typeof import('./src/components/VectorSetProps.vue')['default']
  }
}
