/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimatedModel: typeof import('./src/components/AnimatedModel.vue')['default']
    Cameras: typeof import('./src/components/Cameras.vue')['default']
    FBXModels: typeof import('./src/components/FBXModels.vue')['default']
    Gltf: typeof import('./src/components/gltf/index.vue')['default']
    MeshWobbleMaterial: typeof import('./src/components/meshWobbleMaterial/index.vue')['default']
    MultipleCanvas: typeof import('./src/components/MultipleCanvas.vue')['default']
    PortalJourney: typeof import('./src/components/portal-journey/index.vue')['default']
    Responsiveness: typeof import('./src/components/Responsiveness.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShadersExperiment: typeof import('./src/components/shaders-experiment/index.vue')['default']
    TestSphere: typeof import('./src/components/TestSphere.vue')['default']
    Text3D: typeof import('./src/components/Text3D.vue')['default']
    TheBasic: typeof import('./src/components/TheBasic.vue')['default']
    TheConditional: typeof import('./src/components/TheConditional.vue')['default']
    TheEnvironment: typeof import('./src/components/TheEnvironment.vue')['default']
    TheEvents: typeof import('./src/components/TheEvents.vue')['default']
    TheExperience: typeof import('./src/components/TheExperience.vue')['default']
    TheFireFlies: typeof import('./src/components/portal-journey/TheFireFlies.vue')['default']
    TheFirstScene: typeof import('./src/components/TheFirstScene.vue')['default']
    TheGizmos: typeof import('./src/components/TheGizmos.vue')['default']
    TheGroups: typeof import('./src/components/TheGroups.vue')['default']
    TheModel: typeof import('./src/components/gltf/TheModel.vue')['default']
    TheParticles: typeof import('./src/components/TheParticles.vue')['default']
    ThePortal: typeof import('./src/components/portal-journey/ThePortal.vue')['default']
    TheSmallExperience: typeof import('./src/components/TheSmallExperience.vue')['default']
    TheSphere: typeof import('./src/components/TheSphere.vue')['default']
    VectorSetProps: typeof import('./src/components/VectorSetProps.vue')['default']
  }
}
