/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Gltf: typeof import('./src/components/gltf/index.vue')['default']
    LeviosoDemo: typeof import('./src/components/LeviosoDemo.vue')['default']
    MapControlsDemo: typeof import('./src/components/MapControlsDemo.vue')['default']
    ModelsDemo: typeof import('./src/components/ModelsDemo.vue')['default']
    PointerLockControlsDemo: typeof import('./src/components/PointerLockControlsDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheGizmos: typeof import('./src/components/TheGizmos.vue')['default']
    TheSmoke: typeof import('./src/components/TheSmoke.vue')['default']
    TheStars: typeof import('./src/components/TheStars.vue')['default']
    TheText3D: typeof import('./src/components/TheText3D.vue')['default']
    WobbleMaterial: typeof import('./src/components/WobbleMaterial.vue')['default']
  }
}
