/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Feather: typeof import('./.vitepress/theme/components/Feather.vue')['default']
    LeviosoDemo: typeof import('./.vitepress/theme/components/LeviosoDemo.vue')['default']
    LoveVueThreeJS: typeof import('./.vitepress/theme/components/LoveVueThreeJS.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WobbleMaterial: typeof import('./.vitepress/theme/components/WobbleMaterial.vue')['default']
  }
}
