/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./.vitepress/theme/components/Test copy.vue')['default']
    GettingStartedDemo: typeof import('./.vitepress/theme/components/GettingStartedDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./.vitepress/theme/components/Test.vue')['default']
  }
}
